export const HARDCODING_L2 = {
  Books: [
    {
      No: 1,
      LevelName: 'EB-2A-513',
      LevelRoundId: 5285,
      TopicTitle: 'Dark of the Earth',
      SurfaceImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/br/covernew1/eb-2a-513.jpg',
      StudyImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/dodoabc/cover/eb-2a-513.jpg',
      BookPoint: 8.2,
      RgPointCount: 1,
      RgPointSum: 8.2,
      AddYn: true,
      TodayStudyYn: false,
      AddStudyCount: 22,
      TotalCount: 30,
      PreferenceAverage: 40,
      SeriesName: 'Magic Adventures',
      AnimationPath: '',
      RecommendedAge: 'A',
      WorkBookPrintYn: false,
      StudentWorkSheetYn: true,
      WorkSheetPath: '',
      GetableRgPoint: 4.1,
    },
    {
      No: 2,
      LevelName: 'EB-2A-013',
      LevelRoundId: 3651,
      TopicTitle: 'The Ainu',
      SurfaceImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/br/covernew1/eb-2a-013.jpg',
      StudyImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/dodoabc/cover/eb-2a-013.jpg',
      BookPoint: 8.3,
      RgPointCount: 1,
      RgPointSum: 8.3,
      AddYn: true,
      TodayStudyYn: false,
      AddStudyCount: 22,
      TotalCount: 30,
      PreferenceAverage: 38,
      SeriesName: '',
      AnimationPath: '',
      RecommendedAge: 'A',
      WorkBookPrintYn: true,
      StudentWorkSheetYn: true,
      WorkSheetPath:
        'https://wcfresource.a1edu.com/newsystem/image/worksheet/pdf/ws_eb2a013.pdf',
      GetableRgPoint: 4.1,
    },
    {
      No: 3,
      LevelName: 'EB-2A-314',
      LevelRoundId: 4548,
      TopicTitle: 'How the Elephant Got Her Trunk',
      SurfaceImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/br/covernew1/eb-2a-314.jpg',
      StudyImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/dodoabc/cover/eb-2a-314.jpg',
      BookPoint: 9.3,
      RgPointCount: 0,
      RgPointSum: 0,
      AddYn: true,
      TodayStudyYn: false,
      AddStudyCount: 22,
      TotalCount: 30,
      PreferenceAverage: 39,
      SeriesName: '',
      AnimationPath: '',
      RecommendedAge: 'A',
      WorkBookPrintYn: false,
      StudentWorkSheetYn: true,
      WorkSheetPath: '',
      GetableRgPoint: 9.31,
    },
    {
      No: 4,
      LevelName: 'EB-2A-215',
      LevelRoundId: 3153,
      TopicTitle: 'Henry, Where Were You?',
      SurfaceImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/br/covernew1/eb-2a-215.jpg',
      StudyImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/dodoabc/cover/eb-2a-215.jpg',
      BookPoint: 8.7,
      RgPointCount: 1,
      RgPointSum: 4.35,
      AddYn: true,
      TodayStudyYn: false,
      AddStudyCount: 22,
      TotalCount: 30,
      PreferenceAverage: 39,
      SeriesName: 'Britannica (YCE)',
      AnimationPath: '',
      RecommendedAge: 'A',
      WorkBookPrintYn: true,
      StudentWorkSheetYn: true,
      WorkSheetPath:
        'https://wcfresource.a1edu.com/newsystem/image/worksheet/pdf/ws_eb2a215.pdf',
      GetableRgPoint: 8.7,
    },
    {
      No: 5,
      LevelName: 'EB-2A-386',
      LevelRoundId: 6391,
      TopicTitle: "Princess Suque's Pony",
      SurfaceImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/br/covernew1/eb-2a-386.jpg',
      StudyImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/dodoabc/cover/eb-2a-386.jpg',
      BookPoint: 8.6,
      RgPointCount: 0,
      RgPointSum: 0,
      AddYn: true,
      TodayStudyYn: false,
      AddStudyCount: 22,
      TotalCount: 30,
      PreferenceAverage: 39,
      SeriesName: 'Little Princesses',
      AnimationPath: '',
      RecommendedAge: 'A',
      WorkBookPrintYn: false,
      StudentWorkSheetYn: true,
      WorkSheetPath: '',
      GetableRgPoint: 8.6,
    },
    {
      No: 6,
      LevelName: 'EB-2A-514',
      LevelRoundId: 5275,
      TopicTitle: 'Dark in the City of Lights',
      SurfaceImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/br/covernew1/eb-2a-514.jpg',
      StudyImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/dodoabc/cover/eb-2a-514.jpg',
      BookPoint: 8.2,
      RgPointCount: 1,
      RgPointSum: 8.2,
      AddYn: true,
      TodayStudyYn: false,
      AddStudyCount: 22,
      TotalCount: 30,
      PreferenceAverage: 40,
      SeriesName: 'Magic Adventures',
      AnimationPath: '',
      RecommendedAge: 'A',
      WorkBookPrintYn: false,
      StudentWorkSheetYn: true,
      WorkSheetPath: '',
      GetableRgPoint: 4.1,
    },
    {
      No: 7,
      LevelName: 'EB-2A-014',
      LevelRoundId: 3191,
      TopicTitle: 'Romani Gypsies',
      SurfaceImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/br/covernew1/eb-2a-014.jpg',
      StudyImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/dodoabc/cover/eb-2a-014.jpg',
      BookPoint: 8.3,
      RgPointCount: 1,
      RgPointSum: 8.3,
      AddYn: true,
      TodayStudyYn: false,
      AddStudyCount: 22,
      TotalCount: 30,
      PreferenceAverage: 38,
      SeriesName: '',
      AnimationPath: '',
      RecommendedAge: 'A',
      WorkBookPrintYn: true,
      StudentWorkSheetYn: true,
      WorkSheetPath:
        'https://wcfresource.a1edu.com/newsystem/image/worksheet/pdf/ws_eb2a014.pdf',
      GetableRgPoint: 4.1,
    },
    {
      No: 8,
      LevelName: 'EB-2A-315',
      LevelRoundId: 5148,
      TopicTitle: 'Maria Feels....',
      SurfaceImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/br/covernew1/eb-2a-315.jpg',
      StudyImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/dodoabc/cover/eb-2a-315.jpg',
      BookPoint: 9.6,
      RgPointCount: 0,
      RgPointSum: 0,
      AddYn: true,
      TodayStudyYn: false,
      AddStudyCount: 22,
      TotalCount: 30,
      PreferenceAverage: 39,
      SeriesName: 'Sharing Your Feelings',
      AnimationPath: '',
      RecommendedAge: 'A',
      WorkBookPrintYn: false,
      StudentWorkSheetYn: true,
      WorkSheetPath: '',
      GetableRgPoint: 9.6,
    },
    {
      No: 9,
      LevelName: 'EB-2A-216',
      LevelRoundId: 3472,
      TopicTitle: 'Tim, the Spaceman',
      SurfaceImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/br/covernew1/eb-2a-216.jpg',
      StudyImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/dodoabc/cover/eb-2a-216.jpg',
      BookPoint: 9,
      RgPointCount: 1,
      RgPointSum: 4.5,
      AddYn: true,
      TodayStudyYn: false,
      AddStudyCount: 22,
      TotalCount: 30,
      PreferenceAverage: 38,
      SeriesName: 'Britannica (YCE)',
      AnimationPath: '',
      RecommendedAge: 'A',
      WorkBookPrintYn: true,
      StudentWorkSheetYn: true,
      WorkSheetPath:
        'https://wcfresource.a1edu.com/newsystem/image/worksheet/pdf/ws_eb2a216.pdf',
      GetableRgPoint: 9,
    },
    {
      No: 10,
      LevelName: 'EB-2A-387',
      LevelRoundId: 6408,
      TopicTitle: 'Bet and the Hygiene',
      SurfaceImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/br/covernew1/eb-2a-387.jpg',
      StudyImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/dodoabc/cover/eb-2a-387.jpg',
      BookPoint: 8.5,
      RgPointCount: 0,
      RgPointSum: 0,
      AddYn: true,
      TodayStudyYn: false,
      AddStudyCount: 22,
      TotalCount: 30,
      PreferenceAverage: 39,
      SeriesName: 'Healthy Habits Series',
      AnimationPath: '',
      RecommendedAge: 'A',
      WorkBookPrintYn: false,
      StudentWorkSheetYn: true,
      WorkSheetPath: '',
      GetableRgPoint: 8.5,
    },
    {
      No: 11,
      LevelName: 'EB-2A-515',
      LevelRoundId: 5276,
      TopicTitle: 'The Dark Woods',
      SurfaceImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/br/covernew1/eb-2a-515.jpg',
      StudyImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/dodoabc/cover/eb-2a-515.jpg',
      BookPoint: 8.5,
      RgPointCount: 1,
      RgPointSum: 8.5,
      AddYn: true,
      TodayStudyYn: false,
      AddStudyCount: 22,
      TotalCount: 30,
      PreferenceAverage: 40,
      SeriesName: 'Magic Adventures',
      AnimationPath: '',
      RecommendedAge: 'A',
      WorkBookPrintYn: false,
      StudentWorkSheetYn: true,
      WorkSheetPath: '',
      GetableRgPoint: 4.2,
    },
    {
      No: 12,
      LevelName: 'EB-2A-015',
      LevelRoundId: 3188,
      TopicTitle: 'The Cham People',
      SurfaceImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/br/covernew1/eb-2a-015.jpg',
      StudyImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/dodoabc/cover/eb-2a-015.jpg',
      BookPoint: 8.4,
      RgPointCount: 1,
      RgPointSum: 8.4,
      AddYn: true,
      TodayStudyYn: false,
      AddStudyCount: 22,
      TotalCount: 30,
      PreferenceAverage: 38,
      SeriesName: '',
      AnimationPath: '',
      RecommendedAge: 'A',
      WorkBookPrintYn: true,
      StudentWorkSheetYn: true,
      WorkSheetPath:
        'https://wcfresource.a1edu.com/newsystem/image/worksheet/pdf/ws_eb2a015.pdf',
      GetableRgPoint: 4.2,
    },
    {
      No: 13,
      LevelName: 'EB-2A-316',
      LevelRoundId: 5119,
      TopicTitle: 'Maria Learns....',
      SurfaceImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/br/covernew1/eb-2a-316.jpg',
      StudyImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/dodoabc/cover/eb-2a-316.jpg',
      BookPoint: 11.8,
      RgPointCount: 0,
      RgPointSum: 0,
      AddYn: true,
      TodayStudyYn: false,
      AddStudyCount: 22,
      TotalCount: 30,
      PreferenceAverage: 40,
      SeriesName: 'Sharing Your Feelings',
      AnimationPath: '',
      RecommendedAge: 'A',
      WorkBookPrintYn: false,
      StudentWorkSheetYn: true,
      WorkSheetPath: '',
      GetableRgPoint: 11.8,
    },
    {
      No: 14,
      LevelName: 'EB-2A-217',
      LevelRoundId: 3537,
      TopicTitle: 'The Magic Sausage',
      SurfaceImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/br/covernew1/eb-2a-217.jpg',
      StudyImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/dodoabc/cover/eb-2a-217.jpg',
      BookPoint: 9.5,
      RgPointCount: 1,
      RgPointSum: 4.75,
      AddYn: true,
      TodayStudyYn: false,
      AddStudyCount: 22,
      TotalCount: 30,
      PreferenceAverage: 39,
      SeriesName: 'Britannica (YCE)',
      AnimationPath: '',
      RecommendedAge: 'A',
      WorkBookPrintYn: true,
      StudentWorkSheetYn: true,
      WorkSheetPath:
        'https://wcfresource.a1edu.com/newsystem/image/worksheet/pdf/ws_eb2a217.pdf',
      GetableRgPoint: 9.5,
    },
    {
      No: 15,
      LevelName: 'EB-2A-388',
      LevelRoundId: 6418,
      TopicTitle: 'Nil and the Diet',
      SurfaceImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/br/covernew1/eb-2a-388.jpg',
      StudyImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/dodoabc/cover/eb-2a-388.jpg',
      BookPoint: 8.4,
      RgPointCount: 0,
      RgPointSum: 0,
      AddYn: true,
      TodayStudyYn: false,
      AddStudyCount: 22,
      TotalCount: 30,
      PreferenceAverage: 39,
      SeriesName: 'Healthy Habits Series',
      AnimationPath: '',
      RecommendedAge: 'A',
      WorkBookPrintYn: false,
      StudentWorkSheetYn: true,
      WorkSheetPath: '',
      GetableRgPoint: 8.4,
    },
    {
      No: 16,
      LevelName: 'EB-2A-516',
      LevelRoundId: 5266,
      TopicTitle: "Dark's Africa",
      SurfaceImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/br/covernew1/eb-2a-516.jpg',
      StudyImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/dodoabc/cover/eb-2a-516.jpg',
      BookPoint: 8.4,
      RgPointCount: 1,
      RgPointSum: 8.4,
      AddYn: true,
      TodayStudyYn: false,
      AddStudyCount: 22,
      TotalCount: 30,
      PreferenceAverage: 40,
      SeriesName: 'Magic Adventures',
      AnimationPath: '',
      RecommendedAge: 'A',
      WorkBookPrintYn: false,
      StudentWorkSheetYn: true,
      WorkSheetPath: '',
      GetableRgPoint: 4.2,
    },
    {
      No: 17,
      LevelName: 'EB-2A-016',
      LevelRoundId: 3190,
      TopicTitle: "Uyghurs, China's Muslim Minority",
      SurfaceImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/br/covernew1/eb-2a-016.jpg',
      StudyImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/dodoabc/cover/eb-2a-016.jpg',
      BookPoint: 8.4,
      RgPointCount: 1,
      RgPointSum: 8.4,
      AddYn: true,
      TodayStudyYn: false,
      AddStudyCount: 22,
      TotalCount: 30,
      PreferenceAverage: 38,
      SeriesName: '',
      AnimationPath: '',
      RecommendedAge: 'A',
      WorkBookPrintYn: true,
      StudentWorkSheetYn: true,
      WorkSheetPath:
        'https://wcfresource.a1edu.com/newsystem/image/worksheet/pdf/ws_eb2a016.pdf',
      GetableRgPoint: 4.2,
    },
    {
      No: 18,
      LevelName: 'EB-2A-317',
      LevelRoundId: 5120,
      TopicTitle: 'Maria Remembers....',
      SurfaceImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/br/covernew1/eb-2a-317.jpg',
      StudyImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/dodoabc/cover/eb-2a-317.jpg',
      BookPoint: 11.8,
      RgPointCount: 0,
      RgPointSum: 0,
      AddYn: true,
      TodayStudyYn: false,
      AddStudyCount: 22,
      TotalCount: 30,
      PreferenceAverage: 40,
      SeriesName: 'Sharing Your Feelings',
      AnimationPath: '',
      RecommendedAge: 'A',
      WorkBookPrintYn: false,
      StudentWorkSheetYn: true,
      WorkSheetPath: '',
      GetableRgPoint: 11.8,
    },
    {
      No: 19,
      LevelName: 'EB-2A-218',
      LevelRoundId: 3241,
      TopicTitle: 'Learning The Rules',
      SurfaceImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/br/covernew1/eb-2a-218.jpg',
      StudyImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/dodoabc/cover/eb-2a-218.jpg',
      BookPoint: 8.7,
      RgPointCount: 1,
      RgPointSum: 4.35,
      AddYn: true,
      TodayStudyYn: false,
      AddStudyCount: 22,
      TotalCount: 30,
      PreferenceAverage: 38,
      SeriesName: 'Britannica (YCE)',
      AnimationPath: '',
      RecommendedAge: 'A',
      WorkBookPrintYn: true,
      StudentWorkSheetYn: true,
      WorkSheetPath:
        'https://wcfresource.a1edu.com/newsystem/image/worksheet/pdf/ws_eb2a218.pdf',
      GetableRgPoint: 8.7,
    },
    {
      No: 20,
      LevelName: 'EB-2A-389',
      LevelRoundId: 6512,
      TopicTitle: 'Roc and the Health',
      SurfaceImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/br/covernew1/eb-2a-389.jpg',
      StudyImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/dodoabc/cover/eb-2a-389.jpg',
      BookPoint: 8.5,
      RgPointCount: 0,
      RgPointSum: 0,
      AddYn: true,
      TodayStudyYn: false,
      AddStudyCount: 22,
      TotalCount: 30,
      PreferenceAverage: 39,
      SeriesName: 'Healthy Habits Series',
      AnimationPath: '',
      RecommendedAge: 'A',
      WorkBookPrintYn: false,
      StudentWorkSheetYn: true,
      WorkSheetPath: '',
      GetableRgPoint: 8.5,
    },
    {
      No: 21,
      LevelName: 'EB-2A-517',
      LevelRoundId: 5267,
      TopicTitle: 'Dark Ice',
      SurfaceImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/br/covernew1/eb-2a-517.jpg',
      StudyImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/dodoabc/cover/eb-2a-517.jpg',
      BookPoint: 8.7,
      RgPointCount: 1,
      RgPointSum: 8.7,
      AddYn: true,
      TodayStudyYn: false,
      AddStudyCount: 22,
      TotalCount: 30,
      PreferenceAverage: 40,
      SeriesName: 'Magic Adventures',
      AnimationPath: '',
      RecommendedAge: 'A',
      WorkBookPrintYn: false,
      StudentWorkSheetYn: true,
      WorkSheetPath: '',
      GetableRgPoint: 4.3,
    },
    {
      No: 22,
      LevelName: 'EB-2A-017',
      LevelRoundId: 3650,
      TopicTitle: 'The Tribes of Papua New Guinea',
      SurfaceImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/br/covernew1/eb-2a-017.jpg',
      StudyImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/dodoabc/cover/eb-2a-017.jpg',
      BookPoint: 8.4,
      RgPointCount: 1,
      RgPointSum: 8.4,
      AddYn: true,
      TodayStudyYn: false,
      AddStudyCount: 22,
      TotalCount: 30,
      PreferenceAverage: 38,
      SeriesName: '',
      AnimationPath: '',
      RecommendedAge: 'A',
      WorkBookPrintYn: true,
      StudentWorkSheetYn: true,
      WorkSheetPath:
        'https://wcfresource.a1edu.com/newsystem/image/worksheet/pdf/ws_eb2a017.pdf',
      GetableRgPoint: 4.2,
    },
    {
      No: 23,
      LevelName: 'EB-2A-318',
      LevelRoundId: 5121,
      TopicTitle: 'Daddy Lost His Job',
      SurfaceImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/br/covernew1/eb-2a-318.jpg',
      StudyImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/dodoabc/cover/eb-2a-318.jpg',
      BookPoint: 9.2,
      RgPointCount: 2,
      RgPointSum: 13.799999999999999,
      AddYn: true,
      TodayStudyYn: false,
      AddStudyCount: 22,
      TotalCount: 30,
      PreferenceAverage: 39,
      SeriesName: 'Life Lessons',
      AnimationPath: '',
      RecommendedAge: 'A',
      WorkBookPrintYn: false,
      StudentWorkSheetYn: true,
      WorkSheetPath: '',
      GetableRgPoint: 0,
    },
    {
      No: 24,
      LevelName: 'EB-2A-220',
      LevelRoundId: 3181,
      TopicTitle: 'The Little People',
      SurfaceImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/br/covernew1/eb-2a-220.jpg',
      StudyImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/dodoabc/cover/eb-2a-220.jpg',
      BookPoint: 9.6,
      RgPointCount: 1,
      RgPointSum: 4.8,
      AddYn: true,
      TodayStudyYn: false,
      AddStudyCount: 22,
      TotalCount: 30,
      PreferenceAverage: 38,
      SeriesName: 'Britannica (YCE)',
      AnimationPath: '',
      RecommendedAge: 'A',
      WorkBookPrintYn: true,
      StudentWorkSheetYn: true,
      WorkSheetPath:
        'https://wcfresource.a1edu.com/newsystem/image/worksheet/pdf/ws_eb2a220.pdf',
      GetableRgPoint: 9.6,
    },
    {
      No: 25,
      LevelName: 'EB-2A-390',
      LevelRoundId: 6519,
      TopicTitle: 'Mel and the Sport',
      SurfaceImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/br/covernew1/eb-2a-390.jpg',
      StudyImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/dodoabc/cover/eb-2a-390.jpg',
      BookPoint: 8.5,
      RgPointCount: 0,
      RgPointSum: 0,
      AddYn: true,
      TodayStudyYn: false,
      AddStudyCount: 22,
      TotalCount: 30,
      PreferenceAverage: 39,
      SeriesName: 'Healthy Habits Series',
      AnimationPath: '',
      RecommendedAge: 'A',
      WorkBookPrintYn: false,
      StudentWorkSheetYn: true,
      WorkSheetPath: '',
      GetableRgPoint: 8.5,
    },
    {
      No: 26,
      LevelName: 'EB-2A-518',
      LevelRoundId: 5268,
      TopicTitle: "Olivia's Big Fight",
      SurfaceImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/br/covernew1/eb-2a-518.jpg',
      StudyImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/dodoabc/cover/eb-2a-518.jpg',
      BookPoint: 8.6,
      RgPointCount: 1,
      RgPointSum: 8.6,
      AddYn: true,
      TodayStudyYn: false,
      AddStudyCount: 22,
      TotalCount: 30,
      PreferenceAverage: 41,
      SeriesName: 'Magic Adventures',
      AnimationPath: '',
      RecommendedAge: 'A',
      WorkBookPrintYn: false,
      StudentWorkSheetYn: true,
      WorkSheetPath: '',
      GetableRgPoint: 4.3,
    },
    {
      No: 27,
      LevelName: 'EB-2A-018',
      LevelRoundId: 3050,
      TopicTitle: 'Leaning Tower of Pisa',
      SurfaceImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/br/covernew1/eb-2a-018.jpg',
      StudyImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/dodoabc/cover/eb-2a-018.jpg',
      BookPoint: 8.2,
      RgPointCount: 1,
      RgPointSum: 8.2,
      AddYn: false,
      TodayStudyYn: false,
      AddStudyCount: 22,
      TotalCount: 30,
      PreferenceAverage: 38,
      SeriesName: '',
      AnimationPath: '',
      RecommendedAge: 'A',
      WorkBookPrintYn: true,
      StudentWorkSheetYn: true,
      WorkSheetPath:
        'https://wcfresource.a1edu.com/newsystem/image/worksheet/pdf/ws_eb2a018.pdf',
      GetableRgPoint: 4.1,
    },
    {
      No: 28,
      LevelName: 'EB-2A-319',
      LevelRoundId: 5122,
      TopicTitle: 'Studying Is Hard',
      SurfaceImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/br/covernew1/eb-2a-319.jpg',
      StudyImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/dodoabc/cover/eb-2a-319.jpg',
      BookPoint: 9.1,
      RgPointCount: 1,
      RgPointSum: 9.1,
      AddYn: true,
      TodayStudyYn: false,
      AddStudyCount: 22,
      TotalCount: 30,
      PreferenceAverage: 39,
      SeriesName: 'Life Lessons',
      AnimationPath: '',
      RecommendedAge: 'A',
      WorkBookPrintYn: false,
      StudentWorkSheetYn: true,
      WorkSheetPath: '',
      GetableRgPoint: 4.5,
    },
    {
      No: 29,
      LevelName: 'EB-2A-224',
      LevelRoundId: 3213,
      TopicTitle: 'Finding New Friends',
      SurfaceImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/br/covernew1/eb-2a-224.jpg',
      StudyImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/dodoabc/cover/eb-2a-224.jpg',
      BookPoint: 9,
      RgPointCount: 1,
      RgPointSum: 9,
      AddYn: true,
      TodayStudyYn: false,
      AddStudyCount: 22,
      TotalCount: 30,
      PreferenceAverage: 39,
      SeriesName: 'Britannica (YCE)',
      AnimationPath: '',
      RecommendedAge: 'A',
      WorkBookPrintYn: true,
      StudentWorkSheetYn: true,
      WorkSheetPath:
        'https://wcfresource.a1edu.com/newsystem/image/worksheet/pdf/ws_eb2a224.pdf',
      GetableRgPoint: 4.5,
    },
    {
      No: 30,
      LevelName: 'EB-2A-391',
      LevelRoundId: 6534,
      TopicTitle: "Violet's Tempest",
      SurfaceImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/br/covernew1/eb-2a-391.jpg',
      StudyImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/dodoabc/cover/eb-2a-391.jpg',
      BookPoint: 8.3,
      RgPointCount: 0,
      RgPointSum: 0,
      AddYn: true,
      TodayStudyYn: false,
      AddStudyCount: 22,
      TotalCount: 30,
      PreferenceAverage: 39,
      SeriesName: '',
      AnimationPath: '',
      RecommendedAge: 'A',
      WorkBookPrintYn: false,
      StudentWorkSheetYn: true,
      WorkSheetPath: '',
      GetableRgPoint: 8.31,
    },
  ],
}
