export const HARDCODING_LP = {
  Books: [
    {
      No: 1,
      LevelName: 'EB-PK-428',
      LevelRoundId: 5999,
      TopicTitle: 'bl/cl',
      SurfaceImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/br/covernew1/eb-pk-428.jpg',
      StudyImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/dodoabc/cover/eb-pk-428.jpg',
      BookPoint: 1,
      RgPointCount: 2,
      RgPointSum: 1.5,
      AddYn: true,
      TodayStudyYn: false,
      AddStudyCount: 22,
      TotalCount: 23,
      PreferenceAverage: 0,
      SeriesName: 'Dodo ABC (Phonics 2)',
      AnimationPath: '',
      RecommendedAge: 'A',
      WorkBookPrintYn: false,
      StudentWorkSheetYn: true,
      WorkSheetPath: '',
      GetableRgPoint: 0,
    },
    {
      No: 2,
      LevelName: 'EB-PK-429',
      LevelRoundId: 6000,
      TopicTitle: 'gl/pl',
      SurfaceImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/br/covernew1/eb-pk-429.jpg',
      StudyImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/dodoabc/cover/eb-pk-429.jpg',
      BookPoint: 1,
      RgPointCount: 2,
      RgPointSum: 1.5,
      AddYn: true,
      TodayStudyYn: false,
      AddStudyCount: 22,
      TotalCount: 23,
      PreferenceAverage: 0,
      SeriesName: 'Dodo ABC (Phonics 2)',
      AnimationPath: '',
      RecommendedAge: 'A',
      WorkBookPrintYn: false,
      StudentWorkSheetYn: true,
      WorkSheetPath: '',
      GetableRgPoint: 0,
    },
    {
      No: 3,
      LevelName: 'EB-PK-430',
      LevelRoundId: 6001,
      TopicTitle: 'br/cr',
      SurfaceImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/br/covernew1/eb-pk-430.jpg',
      StudyImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/dodoabc/cover/eb-pk-430.jpg',
      BookPoint: 1,
      RgPointCount: 2,
      RgPointSum: 1.5,
      AddYn: true,
      TodayStudyYn: false,
      AddStudyCount: 22,
      TotalCount: 23,
      PreferenceAverage: 0,
      SeriesName: 'Dodo ABC (Phonics 2)',
      AnimationPath: '',
      RecommendedAge: 'A',
      WorkBookPrintYn: false,
      StudentWorkSheetYn: true,
      WorkSheetPath: '',
      GetableRgPoint: 0,
    },
    {
      No: 4,
      LevelName: 'EB-PK-431',
      LevelRoundId: 6002,
      TopicTitle: 'dr/fr',
      SurfaceImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/br/covernew1/eb-pk-431.jpg',
      StudyImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/dodoabc/cover/eb-pk-431.jpg',
      BookPoint: 1,
      RgPointCount: 1,
      RgPointSum: 1,
      AddYn: true,
      TodayStudyYn: false,
      AddStudyCount: 22,
      TotalCount: 23,
      PreferenceAverage: 0,
      SeriesName: 'Dodo ABC (Phonics 2)',
      AnimationPath: '',
      RecommendedAge: 'A',
      WorkBookPrintYn: false,
      StudentWorkSheetYn: true,
      WorkSheetPath: '',
      GetableRgPoint: 0.5,
    },
    {
      No: 5,
      LevelName: 'EB-PK-432',
      LevelRoundId: 6003,
      TopicTitle: 'gr/tr',
      SurfaceImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/br/covernew1/eb-pk-432.jpg',
      StudyImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/dodoabc/cover/eb-pk-432.jpg',
      BookPoint: 1,
      RgPointCount: 0,
      RgPointSum: 0,
      AddYn: true,
      TodayStudyYn: false,
      AddStudyCount: 22,
      TotalCount: 23,
      PreferenceAverage: 0,
      SeriesName: 'Dodo ABC (Phonics 2)',
      AnimationPath: '',
      RecommendedAge: 'A',
      WorkBookPrintYn: false,
      StudentWorkSheetYn: true,
      WorkSheetPath: '',
      GetableRgPoint: 1,
    },
    {
      No: 6,
      LevelName: 'EB-PK-433',
      LevelRoundId: 6004,
      TopicTitle: 'sk/sm',
      SurfaceImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/br/covernew1/eb-pk-433.jpg',
      StudyImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/dodoabc/cover/eb-pk-433.jpg',
      BookPoint: 1,
      RgPointCount: 0,
      RgPointSum: 0,
      AddYn: true,
      TodayStudyYn: false,
      AddStudyCount: 22,
      TotalCount: 23,
      PreferenceAverage: 0,
      SeriesName: 'Dodo ABC (Phonics 2)',
      AnimationPath: '',
      RecommendedAge: 'A',
      WorkBookPrintYn: false,
      StudentWorkSheetYn: true,
      WorkSheetPath: '',
      GetableRgPoint: 1,
    },
    {
      No: 7,
      LevelName: 'EB-PK-434',
      LevelRoundId: 6005,
      TopicTitle: 'sn/sp',
      SurfaceImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/br/covernew1/eb-pk-434.jpg',
      StudyImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/dodoabc/cover/eb-pk-434.jpg',
      BookPoint: 1,
      RgPointCount: 1,
      RgPointSum: 1,
      AddYn: true,
      TodayStudyYn: false,
      AddStudyCount: 22,
      TotalCount: 23,
      PreferenceAverage: 0,
      SeriesName: 'Dodo ABC (Phonics 2)',
      AnimationPath: '',
      RecommendedAge: 'A',
      WorkBookPrintYn: false,
      StudentWorkSheetYn: true,
      WorkSheetPath: '',
      GetableRgPoint: 0.5,
    },
    {
      No: 8,
      LevelName: 'EB-PK-435',
      LevelRoundId: 6006,
      TopicTitle: 'st/sw',
      SurfaceImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/br/covernew1/eb-pk-435.jpg',
      StudyImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/dodoabc/cover/eb-pk-435.jpg',
      BookPoint: 1,
      RgPointCount: 2,
      RgPointSum: 1.5,
      AddYn: true,
      TodayStudyYn: false,
      AddStudyCount: 22,
      TotalCount: 23,
      PreferenceAverage: 0,
      SeriesName: 'Dodo ABC (Phonics 2)',
      AnimationPath: '',
      RecommendedAge: 'A',
      WorkBookPrintYn: false,
      StudentWorkSheetYn: true,
      WorkSheetPath: '',
      GetableRgPoint: 0,
    },
    {
      No: 9,
      LevelName: 'EB-PK-436',
      LevelRoundId: 6007,
      TopicTitle: 'sh/ch',
      SurfaceImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/br/covernew1/eb-pk-436.jpg',
      StudyImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/dodoabc/cover/eb-pk-436.jpg',
      BookPoint: 1,
      RgPointCount: 1,
      RgPointSum: 1,
      AddYn: true,
      TodayStudyYn: false,
      AddStudyCount: 22,
      TotalCount: 23,
      PreferenceAverage: 0,
      SeriesName: 'Dodo ABC (Phonics 2)',
      AnimationPath: '',
      RecommendedAge: 'A',
      WorkBookPrintYn: false,
      StudentWorkSheetYn: true,
      WorkSheetPath: '',
      GetableRgPoint: 0.5,
    },
    {
      No: 10,
      LevelName: 'EB-PK-437',
      LevelRoundId: 6008,
      TopicTitle: 'th/ng',
      SurfaceImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/br/covernew1/eb-pk-437.jpg',
      StudyImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/dodoabc/cover/eb-pk-437.jpg',
      BookPoint: 1,
      RgPointCount: 1,
      RgPointSum: 1,
      AddYn: true,
      TodayStudyYn: false,
      AddStudyCount: 22,
      TotalCount: 23,
      PreferenceAverage: 0,
      SeriesName: 'Dodo ABC (Phonics 2)',
      AnimationPath: '',
      RecommendedAge: 'A',
      WorkBookPrintYn: false,
      StudentWorkSheetYn: true,
      WorkSheetPath: '',
      GetableRgPoint: 0.5,
    },
    {
      No: 11,
      LevelName: 'EB-PK-438',
      LevelRoundId: 6009,
      TopicTitle: 'ck/nk',
      SurfaceImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/br/covernew1/eb-pk-438.jpg',
      StudyImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/dodoabc/cover/eb-pk-438.jpg',
      BookPoint: 1,
      RgPointCount: 1,
      RgPointSum: 1,
      AddYn: true,
      TodayStudyYn: false,
      AddStudyCount: 22,
      TotalCount: 23,
      PreferenceAverage: 0,
      SeriesName: 'Dodo ABC (Phonics 2)',
      AnimationPath: '',
      RecommendedAge: 'A',
      WorkBookPrintYn: false,
      StudentWorkSheetYn: true,
      WorkSheetPath: '',
      GetableRgPoint: 0.5,
    },
    {
      No: 12,
      LevelName: 'EB-PK-439',
      LevelRoundId: 6010,
      TopicTitle: 'ph/wh',
      SurfaceImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/br/covernew1/eb-pk-439.jpg',
      StudyImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/dodoabc/cover/eb-pk-439.jpg',
      BookPoint: 1,
      RgPointCount: 1,
      RgPointSum: 1,
      AddYn: true,
      TodayStudyYn: false,
      AddStudyCount: 22,
      TotalCount: 23,
      PreferenceAverage: 0,
      SeriesName: 'Dodo ABC (Phonics 2)',
      AnimationPath: '',
      RecommendedAge: 'A',
      WorkBookPrintYn: false,
      StudentWorkSheetYn: true,
      WorkSheetPath: '',
      GetableRgPoint: 0.5,
    },
    {
      No: 13,
      LevelName: 'EB-PK-440',
      LevelRoundId: 6011,
      TopicTitle: 'kn/wr',
      SurfaceImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/br/covernew1/eb-pk-440.jpg',
      StudyImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/dodoabc/cover/eb-pk-440.jpg',
      BookPoint: 1,
      RgPointCount: 1,
      RgPointSum: 1,
      AddYn: true,
      TodayStudyYn: false,
      AddStudyCount: 22,
      TotalCount: 23,
      PreferenceAverage: 0,
      SeriesName: 'Dodo ABC (Phonics 2)',
      AnimationPath: '',
      RecommendedAge: 'A',
      WorkBookPrintYn: false,
      StudentWorkSheetYn: true,
      WorkSheetPath: '',
      GetableRgPoint: 0.5,
    },
    {
      No: 14,
      LevelName: 'EB-PK-441',
      LevelRoundId: 6012,
      TopicTitle: 'y',
      SurfaceImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/br/covernew1/eb-pk-441.jpg',
      StudyImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/dodoabc/cover/eb-pk-441.jpg',
      BookPoint: 1,
      RgPointCount: 1,
      RgPointSum: 1,
      AddYn: true,
      TodayStudyYn: false,
      AddStudyCount: 22,
      TotalCount: 23,
      PreferenceAverage: 0,
      SeriesName: 'Dodo ABC (Phonics 2)',
      AnimationPath: '',
      RecommendedAge: 'A',
      WorkBookPrintYn: false,
      StudentWorkSheetYn: true,
      WorkSheetPath: '',
      GetableRgPoint: 0.5,
    },
    {
      No: 15,
      LevelName: 'EB-PK-442',
      LevelRoundId: 6013,
      TopicTitle: 'ay/ai',
      SurfaceImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/br/covernew1/eb-pk-442.jpg',
      StudyImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/dodoabc/cover/eb-pk-442.jpg',
      BookPoint: 1,
      RgPointCount: 1,
      RgPointSum: 1,
      AddYn: true,
      TodayStudyYn: false,
      AddStudyCount: 22,
      TotalCount: 23,
      PreferenceAverage: 0,
      SeriesName: 'Dodo ABC (Phonics 2)',
      AnimationPath: '',
      RecommendedAge: 'A',
      WorkBookPrintYn: false,
      StudentWorkSheetYn: true,
      WorkSheetPath: '',
      GetableRgPoint: 0.5,
    },
    {
      No: 16,
      LevelName: 'EB-PK-443',
      LevelRoundId: 6014,
      TopicTitle: 'ie/igh',
      SurfaceImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/br/covernew1/eb-pk-443.jpg',
      StudyImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/dodoabc/cover/eb-pk-443.jpg',
      BookPoint: 1,
      RgPointCount: 1,
      RgPointSum: 1,
      AddYn: true,
      TodayStudyYn: false,
      AddStudyCount: 22,
      TotalCount: 23,
      PreferenceAverage: 0,
      SeriesName: 'Dodo ABC (Phonics 2)',
      AnimationPath: '',
      RecommendedAge: 'A',
      WorkBookPrintYn: false,
      StudentWorkSheetYn: true,
      WorkSheetPath: '',
      GetableRgPoint: 0.5,
    },
    {
      No: 17,
      LevelName: 'EB-PK-444',
      LevelRoundId: 6015,
      TopicTitle: 'oa/oe',
      SurfaceImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/br/covernew1/eb-pk-444.jpg',
      StudyImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/dodoabc/cover/eb-pk-444.jpg',
      BookPoint: 1,
      RgPointCount: 1,
      RgPointSum: 1,
      AddYn: true,
      TodayStudyYn: false,
      AddStudyCount: 22,
      TotalCount: 23,
      PreferenceAverage: 0,
      SeriesName: 'Dodo ABC (Phonics 2)',
      AnimationPath: '',
      RecommendedAge: 'A',
      WorkBookPrintYn: false,
      StudentWorkSheetYn: true,
      WorkSheetPath: '',
      GetableRgPoint: 0.5,
    },
    {
      No: 18,
      LevelName: 'EB-PK-445',
      LevelRoundId: 6016,
      TopicTitle: 'ew/oo',
      SurfaceImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/br/covernew1/eb-pk-445.jpg',
      StudyImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/dodoabc/cover/eb-pk-445.jpg',
      BookPoint: 1,
      RgPointCount: 1,
      RgPointSum: 1,
      AddYn: true,
      TodayStudyYn: false,
      AddStudyCount: 22,
      TotalCount: 23,
      PreferenceAverage: 0,
      SeriesName: 'Dodo ABC (Phonics 2)',
      AnimationPath: '',
      RecommendedAge: 'A',
      WorkBookPrintYn: false,
      StudentWorkSheetYn: true,
      WorkSheetPath: '',
      GetableRgPoint: 0.5,
    },
    {
      No: 19,
      LevelName: 'EB-PK-446',
      LevelRoundId: 5909,
      TopicTitle: 'au/aw',
      SurfaceImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/br/covernew1/eb-pk-446.jpg',
      StudyImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/dodoabc/cover/eb-pk-446.jpg',
      BookPoint: 1,
      RgPointCount: 1,
      RgPointSum: 1,
      AddYn: true,
      TodayStudyYn: false,
      AddStudyCount: 22,
      TotalCount: 23,
      PreferenceAverage: 0,
      SeriesName: 'Dodo ABC (Phonics 2)',
      AnimationPath: '',
      RecommendedAge: 'A',
      WorkBookPrintYn: false,
      StudentWorkSheetYn: true,
      WorkSheetPath: '',
      GetableRgPoint: 0.5,
    },
    {
      No: 20,
      LevelName: 'EB-PK-447',
      LevelRoundId: 6017,
      TopicTitle: 'ow/ou',
      SurfaceImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/br/covernew1/eb-pk-447.jpg',
      StudyImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/dodoabc/cover/eb-pk-447.jpg',
      BookPoint: 1,
      RgPointCount: 1,
      RgPointSum: 1,
      AddYn: true,
      TodayStudyYn: false,
      AddStudyCount: 22,
      TotalCount: 23,
      PreferenceAverage: 0,
      SeriesName: 'Dodo ABC (Phonics 2)',
      AnimationPath: '',
      RecommendedAge: 'A',
      WorkBookPrintYn: false,
      StudentWorkSheetYn: true,
      WorkSheetPath: '',
      GetableRgPoint: 0.5,
    },
    {
      No: 21,
      LevelName: 'EB-PK-448',
      LevelRoundId: 6018,
      TopicTitle: 'oy/oi',
      SurfaceImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/br/covernew1/eb-pk-448.jpg',
      StudyImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/dodoabc/cover/eb-pk-448.jpg',
      BookPoint: 1,
      RgPointCount: 1,
      RgPointSum: 1,
      AddYn: true,
      TodayStudyYn: false,
      AddStudyCount: 22,
      TotalCount: 23,
      PreferenceAverage: 0,
      SeriesName: 'Dodo ABC (Phonics 2)',
      AnimationPath: '',
      RecommendedAge: 'A',
      WorkBookPrintYn: false,
      StudentWorkSheetYn: true,
      WorkSheetPath: '',
      GetableRgPoint: 0.5,
    },
    {
      No: 22,
      LevelName: 'EB-PK-449',
      LevelRoundId: 6019,
      TopicTitle: 'ar/or',
      SurfaceImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/br/covernew1/eb-pk-449.jpg',
      StudyImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/dodoabc/cover/eb-pk-449.jpg',
      BookPoint: 1,
      RgPointCount: 1,
      RgPointSum: 1,
      AddYn: true,
      TodayStudyYn: false,
      AddStudyCount: 22,
      TotalCount: 23,
      PreferenceAverage: 0,
      SeriesName: 'Dodo ABC (Phonics 2)',
      AnimationPath: '',
      RecommendedAge: 'A',
      WorkBookPrintYn: false,
      StudentWorkSheetYn: true,
      WorkSheetPath: '',
      GetableRgPoint: 0.5,
    },
    {
      No: 23,
      LevelName: 'EB-PK-450',
      LevelRoundId: 6020,
      TopicTitle: 'ir/ur',
      SurfaceImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/br/covernew1/eb-pk-450.jpg',
      StudyImagePath:
        'https://wcfresource.a1edu.com/newsystem/image/dodoabc/cover/eb-pk-450.jpg',
      BookPoint: 1,
      RgPointCount: 2,
      RgPointSum: 1.5,
      AddYn: true,
      TodayStudyYn: false,
      AddStudyCount: 22,
      TotalCount: 23,
      PreferenceAverage: 0,
      SeriesName: 'Dodo ABC (Phonics 2)',
      AnimationPath: '',
      RecommendedAge: 'A',
      WorkBookPrintYn: false,
      StudentWorkSheetYn: true,
      WorkSheetPath: '',
      GetableRgPoint: 0,
    },
  ],
}
